
import * as React from 'react';

export const BlockedPatternIcon = (props: React.SVGProps<SVGSVGElement>) => (
  <svg viewBox="0 0 300 300" xmlns="http://www.w3.org/2000/svg" {...props}>
    <rect
      x="2"
      y="2"
      width="96"
      height="96"
      stroke="currentColor"
      strokeWidth="2"
      rx="15"
      ry="15"
      fill="currentColor"
    />
    <rect
      x="102"
      y="2"
      width="96"
      height="96"
      stroke="currentColor"
      strokeWidth="2"
      rx="15"
      ry="15"
      fill="currentColor"
    />
    <rect
      x="202"
      y="2"
      width="96"
      height="96"
      stroke="currentColor"
      strokeWidth="2"
      rx="15"
      ry="15"
      fill="currentColor"
    />
    <rect
      x="2"
      y="102"
      width="96"
      height="96"
      stroke="currentColor"
      strokeWidth="2"
      rx="15"
      ry="15"
      fill="white"
    />
    <rect
      x="102"
      y="102"
      width="96"
      height="96"
      stroke="currentColor"
      strokeWidth="2"
      rx="15"
      ry="15"
      fill="white"
    />
    <rect
      x="202"
      y="102"
      width="96"
      height="96"
      stroke="currentColor"
      strokeWidth="2"
      rx="15"
      ry="15"
      fill="white"
    />
    <rect
      x="2"
      y="202"
      width="96"
      height="96"
      stroke="currentColor"
      strokeWidth="2"
      rx="15"
      ry="15"
      fill="currentColor"
    />
    <rect
      x="102"
      y="202"
      width="96"
      height="96"
      stroke="currentColor"
      strokeWidth="2"
      rx="15"
      ry="15"
      fill="currentColor"
    />
    <rect
      x="202"
      y="202"
      width="96"
      height="96"
      stroke="currentColor"
      strokeWidth="2"
      rx="15"
      ry="15"
      fill="currentColor"
    />
  </svg>
);
